SECURE_SESSIONID = 'gcdotcom_secure_sessionid'
SESSIONID = 'gcdotcom_sessionid'
SET_COOKIE = 'Set-Cookie'
CSRFTOKEN = 'csrftoken'
CSRFMIDDLEWARETOKEN = 'csrfmiddlewaretoken'
EMAIL = 'email'
PASSWORD = 'password'
REFERER_VAL = 'https://gc.com/login'
LAST_VIEWED = 'last_team_viewed'

BASE_URL = 'https://gc.com'
LOGIN_URI = '/login'
LOGIN_URI = '/do-login'
LOGOUT_URI = '/do-logout'
